version: "2.2"
services:
  jd-seckill:
    container_name: jd-seckill
    restart: always
    image: chinaarjun/jd-seckill-docker:latest
    environment:
      - JD_SECKILL_EID="string"
      - JD_SECKILL_FP="string"
      - JD_SECKILL_SKU_ID=100012043978
      - JD_SECKILL_BUY_TIME="string"
    volumes:
      # 注意配置文件目录是否正确  本地目录：容器内目录
      - ./common/configs/config.ini:/app/config.ini
